export const IPC_CHANNELS = {
  backend: {
    status: "backend:status",
    statusChanged: "backend:status-changed",
    getRuntimeStatus: "backend:get-runtime-status",
    setExecutionProvider: "backend:set-execution-provider",
    assetMetadata: "backend:asset-metadata",
    listAssets: "backend:list-assets",
    countAssets: "backend:count-assets",
    catalogRevision: "backend:catalog-revision",
    getTextEmbeddingCoverage: "backend:get-text-embedding-coverage",
    getOcrModels: "backend:get-ocr-models",
    getSearchModels: "backend:get-search-models",
    search: "backend:search",
    startJob: "backend:start-job",
    cancelJob: "backend:cancel-job",
    subscribeJob: "backend:subscribe-job",
    unsubscribeJob: "backend:unsubscribe-job",
    jobSnapshot: "backend:job-snapshot",
    jobConnection: "backend:job-connection",
    ensureThumbnails: "backend:ensure-thumbnails",
  },
  native: {
    chooseDirectory: "native:choose-directory",
    chooseVisualSearchImage: "native:choose-visual-search-image",
    addToVisualSearch: "native:add-to-visual-search",
    showFileContextMenu: "native:show-file-context-menu",
  },
} as const;
